name = "pumpfaxt-waitlist"
main = "src/server.ts"
compatibility_date = "2022-11-07"
node_compat = true

[[ d1_databases ]]
binding = "DB"
database_name = "pumpfaxt-waitlist"
database_id = "865c0083-f8fe-4554-8da7-9dbd5820ac25"
migrations_dir = "drizzle"

[vars]
FRONTEND_URL="${FRONTEND_URL}"
PRIVY_APP_SECRET="${PRIVY_APP_SECRET}"

[observability.logs]
enabled = true
